### ISSUE TITLE
刷新页面有时报错，地图无法加载

### ISSUE THREAD

**Issue by zswskey** [zuley/vue-gaode#1]
Uncaught Error: 请前置引入高德地图api，参见http://lbs.amap.com/api/javascript-api/gettingstarted/
Unhandled promise rejection TypeError: Cannot read property 'loadUI' of undefined(…)

**Comment by zuley** [comment]
那个可能是Promise的问题，我已经换成 Async await 的方式实现了。我这边暂时没有发现问题，你可以拉一下新的代码试试。

**Comment by xiaohongzhou** [comment]
我刷新页面，页面报错，用的是最新的代码，Async await 的方式，请教一下是什么问题呢
