### ISSUE TITLE
多个Marker怎么区分？怎么给Marker添加点击事件？

### ISSUE THREAD

**Issue by urnorchrislee** [zuley/vue-gaode#7]
<img width="806" alt="wx20181022-194356 2x" src="https://user-images.githubusercontent.com/12442665/47290690-425f0600-d633-11e8-840f-16ed0acfc992.png">

**Comment by zuley** [comment]
@urnorchrislee 具体使用按照高德地图官网的文档即可，
点标记：https://lbs.amap.com/api/javascript-api/guide/overlays/marker#createmarker
覆盖物事件：https://lbs.amap.com/api/javascript-api/guide/events/map_overlay
